# Generated by Django 5.0.14 on 2026-05-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('devolucion_pendiente', 'Devolución Pendiente'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
    ]
