# Generated by Django 5.0.14 on 2026-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_exacta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
