# Generated by Django 5.0.14 on 2026-04-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_producto', models.CharField(help_text='Código único de inventario', max_length=50, unique=True)),
                ('tipo_producto', models.CharField(choices=[('silla', 'Silla'), ('mesa', 'Mesa'), ('sofa', 'Sofá'), ('cama', 'Cama'), ('armario', 'Armario/Gabinete'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('esta_activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar de la web')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('materiales', models.CharField(blank=True, max_length=200)),
                ('dimensiones', models.CharField(blank=True, max_length=100)),
                ('url_miniatura', models.URLField(blank=True, max_length=500, null=True)),
                ('url_modelo_3d', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='Categoria.categoria')),
            ],
        ),
    ]
