# Generated by Django 5.0.14 on 2026-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='url_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='productos/miniaturas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='url_modelo_3d',
            field=models.FileField(blank=True, null=True, upload_to='productos/modelos_3d/'),
        ),
    ]
