# Generated by Django 5.0.14 on 2026-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo del cliente suscrito', max_length=254, unique=True)),
                ('codigo_descuento', models.CharField(blank=True, max_length=20, unique=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('fue_usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
