# Generated by Django 5.0.14 on 2026-05-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(help_text='Ej: #FFFFFF', max_length=7)),
                ('type', models.CharField(choices=[('paint', 'Pintura/Acabado'), ('fabric', 'Tela/Tapizado')], default='paint', max_length=20)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MuebleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(max_length=500)),
                ('wood_type', models.CharField(default='N/A', max_length=100)),
            ],
        ),
    ]
