# Generated by Django 5.0.14 on 2026-05-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueblebase',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
