# Generated by Django 5.0.14 on 2026-06-18 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personalizacion', '0002_mueblebase_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuebleColorModelo3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_modelo_3d', models.FileField(blank=True, null=True, upload_to='personalizacion/modelos_color/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_mueble', to='Personalizacion.colormaterial')),
                ('mueble_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_color', to='Personalizacion.mueblebase')),
            ],
            options={
                'unique_together': {('mueble_base', 'color')},
            },
        ),
    ]
