"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iqt3f#318-$y@u5p%!p)cy%n!e-6f9g&beb#*2@vv0w&1f1o9v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mssql',
    'drf_yasg',
    "corsheaders",



    #APPS Propias
    'APPS.Categoria',
    'APPS.ComboPedidos',
    'APPS.Departamento',
    'APPS.DetallePedidos',
    'APPS.Facturas',
    'APPS.Municipio',
    'APPS.Pago',
    'APPS.Pedidos',
    'APPS.Producto',
    'APPS.VarianteProducto',
    'Seguridad.Usuarios',
    'APPS.Suscripcion',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#Zona para el envio de correos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tumuebleria@gmail.com'  # Tu correo
EMAIL_HOST_PASSWORD = 'tu-contraseña-de-aplicacion' # Contraseña segura de Google


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# La URL pública para el navegador (siempre debe terminar en /)
MEDIA_URL = '/Media/'

# Configuramos la ruta física en el servidor
if os.environ.get('RAILWAY_ENVIRONMENT'):
    # En la nube, usamos una ruta absoluta que conectaremos al Volumen
    MEDIA_ROOT = '/app/media/'
else:
    # En tu computadora local, se sigue guardando en la carpeta de tu proyecto
    MEDIA_ROOT = os.path.join(BASE_DIR, 'Media')


# Permite que Django responda en el dominio de Railway
ALLOWED_HOSTS = [
    'web-production-93930.up.railway.app',
    '.up.railway.app',
    '127.0.0.1',
    'localhost'
]

# Permite iniciar sesión y enviar formularios desde el dominio seguro (https)
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-93930.up.railway.app',
    'https://*.up.railway.app'
]



STATIC_URL = 'static/'

AUTH_USER_MODEL = 'Usuarios.Usuario'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'