"""
Django settings for Config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iqt3f#318-$y@u5p%!p)cy%n!e-6f9g&beb#*2@vv0w&1f1o9v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'mssql',
    'drf_yasg',
    'corsheaders',
    'rest_framework_simplejwt',
    'anymail',



    #APPS Propias
    'APPS.Categoria',
    'APPS.ComboPedidos',
    'APPS.Departamento',
    'APPS.DetallePedidos',
    'APPS.Facturas',
    'APPS.Municipio',
    'APPS.Pago',
    'APPS.Pedidos',
    'APPS.Producto',
    'APPS.VarianteProducto',
    'Seguridad.Usuarios',
    'APPS.Suscripcion',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Config.urls'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Config.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600
    )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Configuración de Anymail para Resend
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get("RESEND_API_KEY"),
}

# El motor de envío ahora es Anymail
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"

# Tu remitente de prueba o en producción (Configúralo en Railway)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "Mueblería Ángela <ventas@angelamuebleria.business>")





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# La URL pública para el navegador (siempre debe terminar en /)
MEDIA_URL = '/media/'

# Configuramos la ruta física en el servidor
if os.environ.get('RAILWAY_ENVIRONMENT'):
    # En la nube, usamos una ruta absoluta que conectaremos al Volumen
    MEDIA_ROOT = '/app/media/'
else:
    # En tu computadora local, se sigue guardando en la carpeta de tu proyecto
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Permite que Django responda en el dominio de Railway
ALLOWED_HOSTS = [
    'web-production-93930.up.railway.app',
    '.up.railway.app',
    'angelamuebleria.business',          # ← Sin https://
    'www.angelamuebleria.business',      # ← Sin https://
    'api.angelamuebleria.business',      # ← AQUI ESTÁ EL SUBDOMINIO DE TU BACKEND
    '127.0.0.1',
    'localhost'
]



# Permite iniciar sesión y enviar formularios desde el dominio seguro (https)
CSRF_TRUSTED_ORIGINS = [
    'https://api.angelamuebleria.business',  # ← Sin el / al final
    'https://angelamuebleria.business',      # ← Tu Frontend de Vite necesita permisos
    'https://www.angelamuebleria.business',
    'https://*.up.railway.app'
]



STATIC_URL = 'static/'

AUTH_USER_MODEL = 'Usuarios.Usuario'

AUTHENTICATION_BACKENDS = [
    'Seguridad.Usuarios.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'