# Generated by Django 5.0.14 on 2026-04-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComboPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Combo 4 Sillas + Mesa', max_length=255)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
