# Generated by Django 5.0.14 on 2026-05-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categoria', '0001_initial'),
        ('ComboPedidos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del combo', max_length=255)),
                ('tipo_requerido', models.CharField(choices=[('silla', 'Silla'), ('mesa', 'Mesa'), ('sofa', 'Sofá'), ('cama', 'Cama'), ('armario', 'Armario/Gabinete'), ('otro', 'Otro')], default='silla', help_text='Tipo de producto requerido para activar el combo', max_length=20)),
                ('cantidad_requerida', models.PositiveIntegerField(default=4, help_text='Cantidad mínima del producto requerido')),
                ('tipo_regalo', models.CharField(choices=[('silla', 'Silla'), ('mesa', 'Mesa'), ('sofa', 'Sofá'), ('cama', 'Cama'), ('armario', 'Armario/Gabinete'), ('otro', 'Otro')], default='mesa', help_text='Tipo de producto regalado', max_length=20)),
                ('cantidad_regalo', models.PositiveIntegerField(default=1, help_text='Cantidad de productos regalados')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria_regalo', models.ForeignKey(blank=True, help_text='Categoría específica de regalo (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos_regalo', to='Categoria.categoria')),
                ('categoria_requerida', models.ForeignKey(blank=True, help_text='Categoría específica requerida (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos_requeridos', to='Categoria.categoria')),
            ],
        ),
    ]
