# Generated by Django 5.0.14 on 2026-05-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComboPedidos', '0003_reglacombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacombo',
            name='precio_combo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo para el combo (si se establece, sustituye el regalo gratuito)', max_digits=10, null=True),
        ),
    ]
