# Generated by Django 5.0.14 on 2026-05-21 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComboPedidos', '0004_reglacombo_precio_combo'),
        ('Producto', '0002_alter_producto_url_miniatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglacombo',
            name='cantidad_regalo',
        ),
        migrations.RemoveField(
            model_name='reglacombo',
            name='categoria_regalo',
        ),
        migrations.RemoveField(
            model_name='reglacombo',
            name='categoria_requerida',
        ),
        migrations.RemoveField(
            model_name='reglacombo',
            name='tipo_regalo',
        ),
        migrations.RemoveField(
            model_name='reglacombo',
            name='tipo_requerido',
        ),
        migrations.AddField(
            model_name='reglacombo',
            name='cantidad_asociado',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de productos asociados'),
        ),
        migrations.AddField(
            model_name='reglacombo',
            name='producto_asociado',
            field=models.ForeignKey(blank=True, help_text='Producto específico asociado que completa el combo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos_asociados', to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='reglacombo',
            name='producto_requerido',
            field=models.ForeignKey(blank=True, help_text='Producto específico requerido para activar el combo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combos_requeridos', to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='reglacombo',
            name='precio_combo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo para el combo', max_digits=10, null=True),
        ),
    ]
