# Generated by Django 5.0.14 on 2026-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComboPedidos', '0005_remove_reglacombo_cantidad_regalo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacombo',
            name='productos_json',
            field=models.TextField(blank=True, help_text="Lista de productos en formato JSON: [{'producto_id': 1, 'cantidad': 2}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='reglacombo',
            name='cantidad_asociado',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Cantidad de productos asociados', null=True),
        ),
        migrations.AlterField(
            model_name='reglacombo',
            name='cantidad_requerida',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='Cantidad mínima del producto requerido', null=True),
        ),
    ]
