# Generated by Django 5.0.14 on 2026-05-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComboPedidos', '0006_reglacombo_productos_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglacombo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto completa del combo', null=True, upload_to='combos/'),
        ),
    ]
