# Generated by Django 5.0.14 on 2026-04-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetallePedidos', '0001_initial'),
        ('Pedidos', '0001_initial'),
        ('Producto', '0001_initial'),
        ('VarianteProducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Pedidos.pedido'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VarianteProducto.varianteproducto'),
        ),
    ]
