# Generated by Django 5.0.14 on 2026-05-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetallePedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='detalles_personalizacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
