# Generated by Django 5.0.14 on 2026-06-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último request del usuario', null=True),
        ),
    ]
