# Generated by Django 5.0.14 on 2026-04-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('productos', 'Pago de Muebles'), ('delivery', 'Pago de Delivery/Envío')], default='productos', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('tarjeta', 'Tarjeta de Crédito / Débito'), ('transferencia', 'Transferencia Bancaria / Pago Móvil')], max_length=20)),
                ('id_transaccion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('completado', 'Completado'), ('fallido', 'Fallido / Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
