# Generated by Django 5.0.14 on 2026-05-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pago', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/'),
        ),
    ]
